<?php

/**
 * @file
 * A module allowing to change the image background of a website according to the time
 * of the day.
 *
 * This module provides a form that allows to choose three images to display,
 * one in the morning, one in the afternoon, and one during the night.
 */

/**
 * Implements hook_menu().
 */

function changeatmosphere_menu() {
  $items['admin/settings/changeatmosphere'] = array(
    'title' => 'Change Atmosphere Form',
    'description' => 'Form for the Change Atmosphere module',
    'page arguments' => array('changeatmosphere_form'),
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer changeatmosphere'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */

function changeatmosphere_permission() {
  return array(
    'administer changeatmosphere' => array(
      'title' => t('Administer Change Atmosphere module'),
      'description' => t('Configure Change Atmosphere settings.'),
    ),
  );
}

/**
 * Implements hook_form().
 */

function changeatmosphere_form() {
//krumo('test');
//krumo(variable_get('changeatmosphere_morning_image'));
  $form = array ();
  $form['changeatmosphere_morning_image'] = array(
      '#title' => t('Morning Image'),
      '#description' => t('Choose here the image to be displayed in the morning.'),
      '#type' => 'file',
      '#default_value' => variable_get('changeatmosphere_morning_image', ''),
      '#required' => false,
      '#name' => 'files[changeatmosphere_morning_image]'
      );
  $form['changeatmosphere_afternoon_image'] = array(
      '#title' => t('Afternoon Image'),
      '#description' => t('Choose here the image to be displayed in the afternoon.'),
      '#type' => 'file',
      '#default_value' => variable_get('changeatmosphere_afternoon_image', ''),
      '#required' => false,
      );
   $form['changeatmosphere_night_image'] = array(
      '#title' => t('Night Image'),
      '#description' => t('Choose here the image to be displayed during the night.'),
      '#type' => 'file',
      '#default_value' => variable_get('changeatmosphere_night_image', ''),
      '#required' => false,
      );
   $form['submit'] = array(
       '#type' => 'submit',
       '#value' => t('Submit'),
       );

   $form['#submit'][] = '_changeatmosphere_submit';

   return $form;
}

function _changeatmosphere_submit($form, &$form_state) {

//   krumo("test");
//   krumo($form);
//   krumo($form_state);

  foreach($form_state['values'] as $imagefile => $nothing) {
    if (strpos($imagefile, 'changeatmosphere') !== false) {
      $dest_dir = file_default_scheme() . '://changeatmosphere/';

      $validators = array('file_validate_extensions' => array('jpg jpeg'));

    //Save file
    if ($file = file_save_upload($imagefile, $validators, $dest_dir)) {
      variable_set($imagefile, $file->uri);
    }
    else {
        //form_set_error($imagefile, 'Could not upload file.');
    }
  }
}
// krumo($form);
// krumo($form_state);

}


function changeatmosphere_cron() {

  function copy_image_for_time($time) {
      $destimage = file_default_scheme() . '://changeatmosphere/changeatmosphere.jpg';
      if ($time = 'morning') {
        // copy morning image to dest image.
        file_unmanaged_copy(variable_get('changeatmosphere_morning_image'), $destimage, FILE_EXISTS_REPLACE);
      }
      elseif ($time = 'afternoon') {
        //copy afternoon image to dest image.
        file_unmanaged_copy(variable_get('changeatmosphere_afternoon_image'), $destimage, FILE_EXISTS_REPLACE);
      }
      elseif ($time = 'night') {
        //copy night image to dest image.
        file_unmanaged_copy(variable_get('changeatmosphere_night_image'), $destimage, FILE_EXISTS_REPLACE);
      }
    }

  $morningfrom = 40000;
  $morningends = 120000;
  $afternoonends = 190000;
  $currentTime = (int) date('Gis');

  //print_r($currentTime);


  if ($currentTime > $morningfrom && $currentTime < $morningends ) {
    copy_image_for_time('morning');
  }
  elseif ($currentTime > $morningends && $currentTime < $afternoonends) {
    copy_image_for_time('afternoon');
  }
  elseif ($currentTime > $afternoonends && $currentTime < $morningfrom) {
    copy_image_for_time('night');
  }
  else {
    drupal_set_message(t('An error occurred and processing did not complete.'), 'error');
  }
}
